kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ray-minimal-notebook
  labels:
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: demo
      from:
        kind: DockerImage
        name: 'quay.io/erikerlandson/ray-minimal-notebook:py-3.6-ray-43570553'
