kind: ConfigMap
apiVersion: v1
metadata:
  name: ray-singleuser-profile
  labels:
    jupyterhub: singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
    profiles:
    - name: Ray Notebook
      images:
      - 'ray-notebook:latest'
      env:
        # this is a workaround that may not be neccesary in the future
        - name: RAY_CLIENT_MODE
          value: '1'
      services:
        ray-cluster:
          resources:
          - name: ray-cluster-template
            path: rayHeadServiceTemplate
          - name: ray-cluster-template
            path: rayWorkerDeploymentTemplate
          # do head last so RAY_CLUSTER is populated correctly below
          - name: ray-cluster-template
            path: rayHeadDeploymentTemplate
          configuration:
            ray_image: 'quay.io/erikerlandson/ray-client-server:latest'
            # number of workers currently disabled due to bug in JH launcher
            # ray_workers: '3'
            head_memory_request: '512Mi'
            worker_memory_request: '512Mi'
          return:
            # This gets name of last item listed in 'resources' above
            RAY_CLUSTER: 'metadata.name'
