apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ray-jh-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: jupyterhub-hub
  namespace: demo
